package com.bll.lnkrecorder.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bll.lnkrecorder.greendao.RecorderBean;

import com.bll.lnkrecorder.greendao.RecorderBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recorderBeanDaoConfig;

    private final RecorderBeanDao recorderBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recorderBeanDaoConfig = daoConfigMap.get(RecorderBeanDao.class).clone();
        recorderBeanDaoConfig.initIdentityScope(type);

        recorderBeanDao = new RecorderBeanDao(recorderBeanDaoConfig, this);

        registerDao(RecorderBean.class, recorderBeanDao);
    }
    
    public void clear() {
        recorderBeanDaoConfig.clearIdentityScope();
    }

    public RecorderBeanDao getRecorderBeanDao() {
        return recorderBeanDao;
    }

}
